version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 908027414219.dkr.ecr.us-east-2.amazonaws.com
  build:
    commands:
      - docker build -t csv-to-xlsx-repo .
      - docker tag csv-to-xlsx-repo:latest 908027414219.dkr.ecr.us-east-2.amazonaws.com/csv-to-xlsx-repo:latest
  post_build:
    commands:
      - docker push 908027414219.dkr.ecr.us-east-2.amazonaws.com/csv-to-xlsx-repo:latest

artifacts:
  files: []
